# Generated by Django 6.0.3 on 2026-03-28 08:08

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("canonical_url", models.URLField(blank=True)),
                ("noindex", models.BooleanField(default=False)),
                ("allow_comments", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to=core.utils.post_image_path)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="posts/thumbnails/"
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[("fa", "Farsi"), ("en", "English"), ("it", "Italian")],
                        max_length=4,
                        verbose_name="Post's Language",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ("-created_at",),
            },
        ),
    ]
