# Generated by Django 6.0.3 on 2026-03-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="review_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
    ]
