# Generated by Django 6.0.3 on 2026-03-31 06:19

from django.db import migrations
from django_ckeditor_5.fields import CKEditor5Field


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=CKEditor5Field(config_name="default"),
        ),
    ]
