# Generated by Django 6.0.3 on 2026-03-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_comment_content_type_shorturl"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="short_code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name="shorturl",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"), name="unique_short_url_per_object"
            ),
        ),
    ]
