# Generated by Django 6.0.3 on 2026-03-31 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_shorturl_short_code_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ["post", "event", "product"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Content Type",
            ),
        ),
    ]
