# Generated by Django 6.0.3 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_comment_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "subject",
                    models.CharField(max_length=200, verbose_name="Subject"),
                ),
                (
                    "message",
                    models.TextField(verbose_name="Message"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Read"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
