# Generated by Django 6.0.3 on 2026-06-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_add_contact_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
            },
        ),
    ]
